VERSION = '0.0.1'
APPNAME = 'betweenness'

srcdir = '.'
blddir = 'build'

def options(opt):
  opt.load('compiler_cxx')

def configure(ctx):
  ctx.load('compiler_cxx')
  # ctx.check_cxx(lib = ['glog', 'gflags'], uselib_store = 'common')
  ctx.env.CXXFLAGS += ['-O2', '-g', '-I/usr/local/include/', '-std=c++0x']
  ctx.env.append_value('LINKFLAGS', ['-L/usr/local/lib/'])


def build(bld):

  IndexList = ['BFSIndex', 'DoubleBFS', 'LandmarkedIndex', 'Zou', 'ClusteredExactIndex', 'BackboneIndex'];

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Graph/DGraph.cc'],
  #     target       = 'DGraph',
  #     includes     = ['.'])

  # bld(features     = 'cxx cprogram',
  #     source       = ['tests/DGraphTest.cc'],
  #     target       = 'DGraphTest',
  #     includes     = ['.'],
  #     use = ['DGraph'])

  bld(features     = 'cxx cxxstlib',
      source       = ['Index/UnboundedLCR/BFSIndex.cc'],
      target       = 'BFSIndex',
      )

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/DoubleBFS.cc'],
  #     target       = 'DoubleBFS',
  #     includes     = ['.'],
  #     use = '')

  bld(features     = 'cxx cxxstlib',
      source       = ['Index/UnboundedLCR/LandmarkedIndex.cc'],
      target       = 'LandmarkedIndex',
      )

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/Zou.cc'],
  #     target       = 'Zou',
  #     includes     = ['.'],
  #     use = '')

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/BackboneIndex.cc'],
  #     target       = 'BackboneIndex',
  #     includes     = ['.'],
  #     use = '')

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/NeighbourExchange.cc'],
  #     target       = 'NeighbourExchange',
  #     includes     = ['.'],
  #     use = '')

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/PartialIndex.cc'],
  #     target       = 'Partial',
  #     includes     = ['.'],
  #     use = '')

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/ClusteredExactIndex.cc'],
  #     target       = 'ClusteredExactIndex',
  #     includes     = ['.'],
  #     use = '')

  bld(features     = 'cxx cprogram',
      source       = ['experiments/genStats.cc'],
      target       = 'genStats',
      use = 'BFSIndex')

  # bld(features     = 'cxx cprogram',
  #     source       = ['experiments/Index/UnboundedLCR/runExperiment.cc'],
  #     target       = 'runExperiment',
  #     includes     = ['.'],
  #     use = IndexList)

  # bld(features     = 'cxx cprogram',
  #     source       = ['experiments/Index/UnboundedLCR/maintenanceExp.cc'],
  #     target       = 'maintenanceExp',
  #     includes     = ['.'],
  #     use = IndexList)

  # bld(features     = 'cxx cprogram',
  #     source       = ['experiments/Index/UnboundedLCR/queryAllExp.cc'],
  #     target       = 'queryAllExp',
  #     includes     = ['.'],
  #     use = IndexList)

  # bld(features     = 'cxx cprogram',
  #     source       = ['experiments/Index/UnboundedLCR/genQuery.cc'],
  #     target       = 'genQuery',
  #     includes     = ['.'],
  #     use = IndexList)

  bld(features     = 'cxx cprogram',
      source       = ['tests/Index/UnboundedLCR/LandmarkedIndexTest.cc'],
      target       = 'LandmarkedIndexTest',
      use = ['LandmarkedIndex'])

  # bld(features     = 'cxx cprogram',
  #     source       = ['tests/Index/UnboundedLCR/DoubleBFSTest.cc'],
  #     target       = 'DoubleBFSTest',
  #     includes     = ['.'],
  #     use = ['LandmarkedIndex'])

  # bld(features     = 'cxx cprogram',
  #     source       = ['tests/Index/UnboundedLCR/BFSTest.cc'],
  #     target       = 'BFSTest',
  #     includes     = ['.'],
  #     use = ['LandmarkedIndex'])

  # bld(features     = 'cxx cprogram',
  #     source       = ['tests/Index/UnboundedLCR/ZouTest.cc'],
  #     target       = 'ZouTest',
  #     includes     = ['.'],
  #     use = ['Zou'])

  # bld(features     = 'cxx cprogram',
  #     source       = ['tests/Index/UnboundedLCR/BackboneIndexTest.cc'],
  #     target       = 'BackboneIndexTest',
  #     includes     = ['.'],
  #     use = ['BackboneIndex'])

  # bld(features     = 'cxx cxxstlib',
  #     source       = ['Index/UnboundedLCR/WD/LandmarkedIndexWD.cc'],
  #     target       = 'LandmarkedIndexWD',
  #     includes     = ['.']
  #     )

  # bld(features     = 'cxx cprogram',
  #     source       = ['tests/Index/UnboundedLCR/WD/LandmarkedIndexWDTest.cc'],
  #     target       = 'LandmarkedIndexWDTest',
  #     includes     = ['.'],
  #     use = ['LandmarkedIndexWD']
  #     )

  # bld(features     = 'cxx cprogram',
  #    source       = ['experiments/Index/UnboundedLCR/runWDExperiment.cc'],
  #    target       = 'runWDExperiment',
  #    includes     = ['.'],
  #    use = ['LandmarkedIndex', 'LandmarkedIndexWD'] )
